Require Python 3.9
build with Python 3.8 seems to fail with

```
In file included from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/pytime.h:6,
                   from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/Python.h:85,
                   from cypari2/convert.c:50:
  cypari2/pycore_long.h: In function '_PyLong_SetSignAndDigitCount':
  cypari2/pycore_long.h:92:13: error: 'o' undeclared (first use in this function); did you mean 'op'?
     92 |     Py_SIZE(o) = size;
        |
```

also our CI only tests with Python 3.9+ so that seem to be required by
now.

In any case, active support for Python 3.8 ended May 2021 and security
support is going to end in October 2024.